# Generated by Django 5.2.6 on 2025-12-01 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Requerido para completar el registro del alumno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='carrera.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(help_text='Identificador único del alumno', max_length=10, unique=True, verbose_name='Legajo'),
        ),
    ]
